import 'package:flutter/material.dart';
import 'package:news_app/models/country.dart';

const kColorPrimary = Color(0xFF0C54BE);
const kColorPrimaryDark = Color(0xFF303F60);
const kColorSecondary = Color(0xFFF5F9FD);
const kColorSecondaryDark = Color(0xFFCED3DC);

final countryList = [
  Country("United Arab Emirates", "ae", 1),
  Country("Argentine", "ar", 2),
  Country("Austria", "at", 3),
  Country("Australia", "au", 4),
  Country("Belgium", "be", 5),
  Country("Bulgaria", "bg", 6),
  Country("Brazil", "br", 7),
  Country("Canada", "ca", 8),
  Country("China", "cn", 9),
  Country("Colombia", "co", 10),
  Country("Cuba", "cu", 11),
  Country("Czech Republic", "cz", 12),
  Country("Germany", "de", 13),
  Country("Egypt", "eg", 14),
  Country("French", "fr", 15),
  Country("United Kingdom of Great Britain and Northern Ireland", "gb", 16),
  Country("Greece", "gr", 17),
  Country("Hong Kong", "hk", 18),
  Country("Hungary", "hu", 19),
  Country("Indonesia", "id", 20),
  Country("Ireland", "ie", 21),
  Country("India", "in", 22),
  Country("Italian", "it", 23),
  Country("Japan", "jp", 24),
  Country("Korea", "kr", 25),
  Country("Lithuania", "lt", 26),
  Country("Latvia", "lv", 27),
  Country("Morocco", "ma", 28),
  Country("Mexico", "mx", 29),
  Country("Malaysia", "my", 30),
  Country("Nigeria", "ng", 31),
  Country("Netherlands", "nl", 32),
  Country("Norway", "no", 33),
  Country("New Zealand", "nz", 34),
  Country("Philippines", "ph", 35),
  Country("Poland", "po", 36),
  Country("Portuguese", "pt", 37),
  Country("Romania", "ro", 38),
  Country("Serbia", "rs", 39),
  Country("Russian", "ru", 40),
  Country("Saudi Arabia", "sa", 41),
  Country("Sweden", "se", 42),
  Country("Singapore", "sg", 43),
  Country("Canada", "ca", 44),
  Country("Slovenia", "si", 45),
  Country("Slovakia", "sk", 46),
  Country("Thailand", "th", 47),
  Country("Turkey", "tr", 48),
  Country("Taiwan", "tw", 49),
  Country("Ukraine", "ua", 50),
  Country("United States of America", "us", 51),
  Country("Venezuela", "ve", 52),
  Country("South Africa", "za", 53),
];
